a = 10
b = 0

# c = a/b
# print(c)

# try:
#     c = a/b
#     print(c)
# except:
#     print('Error occoured')

# try:
#     c = a/b
#     print(c)
# except:
#     print('Error occoured')
# else:
#     print('No errors')


# try:
#     c = a/b
#     print(c)
# except:
#     print('Error occoured')
# else:
#     print('No errors')
# finally:
#     print("Inside Finally")

# print('Outside')

# try:
#     c = a/b
#     print(c)
# except ZeroDivisionError: 
#     print('Division by zero occoured')
# except Exception as e:
#     print('other exception')


# try:
#     c = a/b
#     print(c)
# except ZeroDivisionError:
#     raise ZeroDivisionError('division by zero occoured')

# a = int(input('Enter a number: '))
# b = int(input('Enter a number: '))


# if b == 0:
#     raise ZeroDivisionError('B is zero')
# else:
#     c = a/b
#     print(c)

# assert b > 0, 'B is negative'
# c = a/b
# print(c)


# Summary

try:
    # code to run
    pass
except:
    # code to run if error/exception occoured
    pass
else:
    # if no error occoured
    pass
finally:
    # run everytime
    pass

# assert <expression>, 'Error message'

# raise ExceptionClass('Error message')
